
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author badri
 */
public class home extends javax.swing.JFrame {
      public static int heart = 5;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();  
        jLabel2.setText(String.valueOf(heart + latihansoal.nama1 - latihansoal.nama + messagedialog2.xpplus1));
        jLabel1.setText(String.valueOf("" + register.name));
        xp.setText(String.valueOf(reward1.reward5 + reward.reward6 + reward2.xpplus - messagedialog2.xpplus1));
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xp1 = new javax.swing.JLabel();
        xp = new javax.swing.JLabel();
        board = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 78, 69));
        jLabel4.setText("Hai");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(305, 172, 91, 71);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 78, 69));
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(414, 172, 310, 71);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 78, 69));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/heart.png"))); // NOI18N
        jLabel2.setText("5");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 130, 250, 36);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(113, 134, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/profilepic.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(128, 147, 147, 147);

        xp1.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        xp1.setForeground(new java.awt.Color(147, 147, 147));
        xp1.setText("XP");
        jPanel1.add(xp1);
        xp1.setBounds(1200, 210, 64, 60);

        xp.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        xp.setForeground(new java.awt.Color(147, 147, 147));
        xp.setText("000");
        jPanel1.add(xp);
        xp.setBounds(1077, 210, 100, 60);

        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/board.png"))); // NOI18N
        jPanel1.add(board);
        board.setBounds(840, 170, 468, 146);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tujuan1.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(128, 421, 324, 385);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 62.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(559, 421, 324, 385);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 62 (1).png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(984, 421, 324, 385);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/profile.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(644, 864, 50, 55);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/achieve.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(745, 864, 54, 55);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1335, 45, 65, 73);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 78, 69));
        jLabel6.setText("Yuk selesaikan misi kamu!");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(305, 249, 348, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        
        tujuanpembelajaran tp = new tujuanpembelajaran();
        tp.setVisible(true);
        this.dispose();
        jLabel15.setEnabled(false);
            
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        pengertianteksanekdot pt = new pengertianteksanekdot();
        pt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        latihansoal ls = new latihansoal();
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        register re = new register();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        tukarpencapaian tp1 = new tukarpencapaian();
        tp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel board;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel xp;
    private javax.swing.JLabel xp1;
    // End of variables declaration//GEN-END:variables

  

   
}
