
import java.awt.Color;
import javax.swing.ButtonGroup;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author badri
 */
public class latihansoal extends javax.swing.JFrame {
    public static int nama;
    public static int nama1;
    String[] questions = {"Berikut ini yang bukan ciri-ciri teks anekdot adalah","Berikut ini yang bukan ciri-ciri teks anekdot adalah","Bagian akhir dari cerita dalam struktur teks anekdot disebut...","Aspek yang harus ada dalam struktur teks anekdot, yaitu...","Kalimat yang menunjukkan kalimat seru adalah..."};
    // last item is the correct answer
    String[][] options = {{"A. Struktur teks orientasi-krisis-reaksi","B. Memiliki pesan moral","C. Memiliki unsur lucu","D. Berbentuk cerita"},{"A. Pesan moral, kelucuan/kekonyolan, sindiran, dan kebahasaan.","B. Struktur, pesan moral, sindiran, kelucuan/kekonyolan.","C. Kelucuan/kekonyolan, sindiran, dan kebahasaan.","D. Pesan moral, kelucuan/kekonyolan, sindiran."},{"A.  Abstraksi","B. Orientasi","C. Krisis","D. Koda"},{"A.Krisis-reaksi-koda","B.Orientasi-krisis-koda","C.Orientasi-krisis-reaksi","D.Abstraksi- krisis-koda"},{"A.\"Apakah benar,\" teriak Jaksa.","B.\"Pak, tolong jawab pertanyaan Jaksa.","C. \"Saya pikir dia tadi berbicara dengan Anda.\"","D.\"Oh, maaf!\" Saksi terkejut sambil berkata kepada hakim."}};
int index = 0, correct = 0;
ButtonGroup bg = new ButtonGroup();

    /**
     * Creates new form latihansoal
     */
    public latihansoal() {
        initComponents();
        
        bg.add(jRadioButton1_);
        bg.add(jRadioButton2_);
        bg.add(jRadioButton3_);
        bg.add(jRadioButton4_);
        
        jPanel3_QMouseClicked(null);
    }
    public void getSelectedOption(javax.swing.JRadioButton rbtn)
    {
    // get the selected value from the radiobutton
        // increment the index
        // disable he radiobuttons
        //check if the user selected the right answer
        System.out.println(rbtn.getText());
        System.out.println(options[index][3]);
        if(rbtn.getText().equals(options[index][3]))
        {
            correct++;
        }
        index++;
        enableRbuttons(false);
    }
    // enable/ disable radiobuttons
    public void enableRbuttons(boolean yes_or_no)
    {
        jRadioButton1_.setEnabled(yes_or_no);
        jRadioButton2_.setEnabled(yes_or_no);
        jRadioButton3_.setEnabled(yes_or_no);
        jRadioButton4_.setEnabled(yes_or_no);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3_Q = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4_ = new javax.swing.JRadioButton();
        jRadioButton3_ = new javax.swing.JRadioButton();
        jRadioButton1_ = new javax.swing.JRadioButton();
        jRadioButton2_ = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(253, 103, 101));
        jPanel1.setLayout(null);

        jPanel3_Q.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3_Q.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 178, 245), 10, true));
        jPanel3_Q.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3_QMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3_QMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3_QMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 178, 245));
        jLabel4.setText("Next > ");

        javax.swing.GroupLayout jPanel3_QLayout = new javax.swing.GroupLayout(jPanel3_Q);
        jPanel3_Q.setLayout(jPanel3_QLayout);
        jPanel3_QLayout.setHorizontalGroup(
            jPanel3_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(jPanel3_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3_QLayout.createSequentialGroup()
                    .addGap(0, 120, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 121, Short.MAX_VALUE)))
        );
        jPanel3_QLayout.setVerticalGroup(
            jPanel3_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel3_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3_QLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3_Q);
        jPanel3_Q.setBounds(968, 840, 410, 88);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/heart.png"))); // NOI18N
        jLabel5.setText("5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 870, 160, 40);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 78, 69));
        jLabel3.setText("Question Here??");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 330, 1120, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihan/Home.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1320, 70, 65, 80);

        jRadioButton4_.setFont(new java.awt.Font("Roboto", 0, 35)); // NOI18N
        jRadioButton4_.setText("jRadioButton4");
        jRadioButton4_.setToolTipText("");
        jRadioButton4_.setActionCommand("");
        jRadioButton4_.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jRadioButton4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4_ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4_);
        jRadioButton4_.setBounds(110, 710, 1230, 58);

        jRadioButton3_.setFont(new java.awt.Font("Roboto", 0, 35)); // NOI18N
        jRadioButton3_.setText("jRadioButton3");
        jRadioButton3_.setToolTipText("");
        jRadioButton3_.setActionCommand("");
        jRadioButton3_.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jRadioButton3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3_);
        jRadioButton3_.setBounds(110, 650, 1230, 58);

        jRadioButton1_.setFont(new java.awt.Font("Roboto", 0, 35)); // NOI18N
        jRadioButton1_.setText("jRadioButton1");
        jRadioButton1_.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jRadioButton1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1_);
        jRadioButton1_.setBounds(110, 510, 1230, 58);

        jRadioButton2_.setFont(new java.awt.Font("Roboto", 0, 35)); // NOI18N
        jRadioButton2_.setText("jRadioButton2");
        jRadioButton2_.setActionCommand("");
        jRadioButton2_.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jRadioButton2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2_);
        jRadioButton2_.setBounds(110, 580, 1240, 58);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Group 61.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 0, 1365, 1024);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_ActionPerformed
        getSelectedOption(jRadioButton3_);
    }//GEN-LAST:event_jRadioButton3_ActionPerformed

    private void jRadioButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_ActionPerformed
        getSelectedOption(jRadioButton1_);
    }//GEN-LAST:event_jRadioButton1_ActionPerformed
        
    private void jRadioButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_ActionPerformed
        getSelectedOption(jRadioButton2_);
    }//GEN-LAST:event_jRadioButton2_ActionPerformed

    private void jRadioButton4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4_ActionPerformed
        getSelectedOption(jRadioButton4_);
    }//GEN-LAST:event_jRadioButton4_ActionPerformed

    private void jPanel3_QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_QMouseClicked
        
       
        if(index == questions.length)
        {
        jLabel3.setText("Your Score: " + correct + " / " + questions.length);
        if(correct >= (float) questions.length/2)
        {
           jLabel5.setText("5"); 
           int latihan1 = Integer.parseInt(jLabel5.getText().toString());
           nama = latihan1;
           jLabel5.setText(String.valueOf(nama));
        }else {
           jLabel5.setText("0");
           int latihan = Integer.parseInt(jLabel5.getText().toString());
           nama1 = latihan;
           jLabel5.setText(String.valueOf(nama));
        }
         }
        else{
            // enable radio buttons
        enableRbuttons(true);
        
        jLabel3.setText(questions[index]);
        jRadioButton1_.setText(options[index][0]);
        jRadioButton2_.setText(options[index][1]);
        jRadioButton3_.setText(options[index][2]);
        jRadioButton4_.setText(options[index][3]);
        
        if(index == questions.length-1){
         jLabel4.setText("Lihat hasilnya");
         reward2 re = new reward2();
         re.setVisible(true);
        }
         
    }//GEN-LAST:event_jPanel3_QMouseClicked
          // clear the selection
        bg.clearSelection();
}
    
    private void jPanel3_QMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_QMouseEntered
        jPanel3_Q.setBackground(new Color(32,178,245));
        jLabel4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel3_QMouseEntered

    private void jPanel3_QMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_QMouseExited
        jPanel3_Q.setBackground(Color.WHITE);
        jLabel4.setForeground(new Color(32,178,245));
    }//GEN-LAST:event_jPanel3_QMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        home ho = new home();
        ho.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihansoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihansoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihansoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihansoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihansoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3_Q;
    private javax.swing.JRadioButton jRadioButton1_;
    private javax.swing.JRadioButton jRadioButton2_;
    private javax.swing.JRadioButton jRadioButton3_;
    private javax.swing.JRadioButton jRadioButton4_;
    // End of variables declaration//GEN-END:variables

    private void jPanel3_QActionPerformed(Object object) {
        
    } 
   
      
}
