import java.awt.Color;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author badri
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        mulai = new javax.swing.JPanel();
        lbmulai = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        lbinfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/about.png"))); // NOI18N

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo/logo.gif"))); // NOI18N

        mulai.setBackground(new java.awt.Color(255, 255, 255));
        mulai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 178, 245), 10, true));
        mulai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulai.setPreferredSize(new java.awt.Dimension(273, 92));
        mulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mulaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mulaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mulaiMousePressed(evt);
            }
        });

        lbmulai.setBackground(new java.awt.Color(255, 255, 255));
        lbmulai.setFont(new java.awt.Font("Roboto", 1, 39)); // NOI18N
        lbmulai.setForeground(new java.awt.Color(32, 178, 245));
        lbmulai.setText("MULAI");

        javax.swing.GroupLayout mulaiLayout = new javax.swing.GroupLayout(mulai);
        mulai.setLayout(mulaiLayout);
        mulaiLayout.setHorizontalGroup(
            mulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
            .addGroup(mulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mulaiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbmulai)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mulaiLayout.setVerticalGroup(
            mulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(mulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mulaiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbmulai)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 178, 245), 10, true));
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.setPreferredSize(new java.awt.Dimension(273, 92));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMousePressed(evt);
            }
        });

        lbinfo.setBackground(new java.awt.Color(255, 255, 255));
        lbinfo.setFont(new java.awt.Font("Roboto", 1, 39)); // NOI18N
        lbinfo.setForeground(new java.awt.Color(32, 178, 245));
        lbinfo.setText("INFO");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbinfo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbinfo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logo)
                    .addComponent(about)
                    .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(73, 73, 73)
                .addComponent(about)
                .addGap(127, 127, 127)
                .addComponent(mulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiMouseEntered
        mulai.setBackground(new Color(32,178,245));
        lbmulai.setForeground(Color.WHITE);
    }//GEN-LAST:event_mulaiMouseEntered

    private void mulaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiMouseExited
         mulai.setBackground(Color.WHITE);
        lbmulai.setForeground(new Color(32,178,245));
    }//GEN-LAST:event_mulaiMouseExited

    private void mulaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiMousePressed
        mulai.setBackground(new Color(32,178,245));
        lbmulai.setForeground(Color.WHITE);
    }//GEN-LAST:event_mulaiMousePressed

    private void infoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseEntered
        info.setBackground(new Color(32,178,245));
        lbinfo.setForeground(Color.WHITE);
    }//GEN-LAST:event_infoMouseEntered

    private void infoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseExited
        info.setBackground(Color.WHITE);
        lbinfo.setForeground(new Color(32,178,245));
    }//GEN-LAST:event_infoMouseExited

    private void infoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMousePressed
        
    }//GEN-LAST:event_infoMousePressed

    private void mulaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiMouseClicked
        register Register = new register();
            Register.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_mulaiMouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
        info in = new info();
            in.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_infoMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JLabel lbmulai;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mulai;
    // End of variables declaration//GEN-END:variables

}

