
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author badri
 */
public class tukarpencapaian extends javax.swing.JFrame {
public static int xp4;
    /**
     * Creates new form tukarpencapaian
     */
    public tukarpencapaian() {
        initComponents();
         xp.setText(String.valueOf(reward1.reward5 + reward.reward6 + reward2.xpplus - messagedialog2.xpplus1));
         int x4 = Integer.parseInt(xp.getText().toString());
        xp4 = x4;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        xp1 = new javax.swing.JLabel();
        xp = new javax.swing.JLabel();
        jPanel3_tukar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Home20.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1330, 40, 70, 80);

        xp1.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        xp1.setForeground(new java.awt.Color(147, 147, 147));
        xp1.setText("XP");
        getContentPane().add(xp1);
        xp1.setBounds(320, 880, 64, 60);

        xp.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        xp.setForeground(new java.awt.Color(147, 147, 147));
        xp.setText("000");
        getContentPane().add(xp);
        xp.setBounds(220, 880, 100, 60);

        jPanel3_tukar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3_tukar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 178, 245), 10, true));
        jPanel3_tukar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3_tukar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3_tukarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3_tukarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3_tukarMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 178, 245));
        jLabel4.setText("TUKAR");

        javax.swing.GroupLayout jPanel3_tukarLayout = new javax.swing.GroupLayout(jPanel3_tukar);
        jPanel3_tukar.setLayout(jPanel3_tukarLayout);
        jPanel3_tukarLayout.setHorizontalGroup(
            jPanel3_tukarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(jPanel3_tukarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3_tukarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3_tukarLayout.setVerticalGroup(
            jPanel3_tukarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel3_tukarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3_tukarLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3_tukar);
        jPanel3_tukar.setBounds(1130, 440, 190, 88);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pencapaian.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 0, 1560, 1030);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        setSize(new java.awt.Dimension(1456, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3_tukarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_tukarMouseClicked
        if(xp4<= 5){
        messagedialog1 message = new messagedialog1();
        message.setVisible(true);
        this.dispose();
        }
        else{
        messagedialog2 message = new messagedialog2();
        message.setVisible(true);
        this.dispose();
        }

    }//GEN-LAST:event_jPanel3_tukarMouseClicked

    private void jPanel3_tukarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_tukarMouseEntered
        jPanel3_tukar.setBackground(new Color(32,178,245));
        jLabel4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel3_tukarMouseEntered

    private void jPanel3_tukarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3_tukarMouseExited
        jPanel3_tukar.setBackground(Color.WHITE);
        jLabel4.setForeground(new Color(32,178,245));
    }//GEN-LAST:event_jPanel3_tukarMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        home Home = new home();
        Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tukarpencapaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tukarpencapaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tukarpencapaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tukarpencapaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tukarpencapaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3_tukar;
    private javax.swing.JLabel xp;
    private javax.swing.JLabel xp1;
    // End of variables declaration//GEN-END:variables
}
